### ISSUE TITLE
Reworked version of atari_sound_setup.h

### ISSUE THREAD

**Issue by th-otto** [mikrosk/atari_sound_setup#1]
Hi,

i just wanted to share a slightly reworked version (just attaching it here as a whole, since a patch just looks too confusing)

The major things that i changed:

- external clock test is skipped if hasFreeFrequencies, since the probed values are not used in that case
- the externalClockTest function slightly changed:
   - inserted stop #0x2300 to be more system friendly while waiting for a timer interrupt
   - Changed the bne to bcc. In some cases the exact value of the 200hz counter seems to be missed. That fixes infinite loops in aranym
   - For clarity, just returned the number of ticks, and convert that to the clock type afterwards.
 - Changed the test for machine type to `(cookie_snd & SND_DSP)` instead. Not entirely sure whether there is a better way, but atleast it should not depend on the machine type (previously it would be skipped if you have that set to MCH_ARANYM, and also on clones like Hades/Milan/Firebee),

There are still some issues that could be fixed:
- The function returns immediately, when Locksnd() returns != 1. This will work when using EmuTOS, but not on STE/TT when no other sound driver is installed.
- The Devconnect function in TOS 4.04 is buggy when trying to set CLKEXT. Again, this should work correctly in EmuTOS. SDL (https://github.com/libsdl-org/SDL-1.2/blob/f5f2d3825637169fc8f3ebc6ef0d076916e27e82/src/audio/mint/SDL_mintaudio_xbios.c#L194) attempts to replace that function, at the cost of directly banging at the hardware. Maybe that replacement is also why SDL sound does not work on the firebee.
- The external clock test does not work reliable in aranym. Even after a few fixes to support 2 external clocks, i get slightly different values as was the function expects. But this seems to be aranym specific. Currently i get values between 31-38 for the 48k clock test, and between 41-45 for the 44.1 clock test.

[atari_sound_setup.h.txt](https://github.com/mikrosk/atari_sound_setup/files/14831961/atari_sound_setup.h.txt)

**Comment by mikrosk** [comment]
Thanks for the patch, looks good to me.

> The function returns immediately, when Locksnd() returns != 1. This will work when using EmuTOS, but not on STE/TT when no other sound driver is installed.

In what way it doesn't work? If there is no driver installed, it is supposed to return, that's the whole point of the check.

> The Devconnect function in TOS 4.04 is buggy when trying to set CLKEXT

No, it is buggy in TOS 4.01/4.02, it had been fixed in 4.04. I have it in my notes but so far nobody has complained. 

> The external clock test does not work reliable in aranym

That should be fixed on the aranym side, then. The values are derived from real Falcon's behaviour and proven by at least two decades of usage.

**Comment by th-otto** [comment]
> In what way it doesn't work? If there is no driver installed, it is supposed to return, that's the whole point of the check.

That would be the on STE/TT. Aren't the routines supposed to work in that case?

> No, it is buggy in TOS 4.01/4.02, it had been fixed in 4.04. I have it in my notes but so far nobody has complained.

No, it is still buggy in 4.04:

```
extclk:
[00e065f6] 302f 000a                 move.w    10(a7),d0
[00e065fa] 0279 00ff 00ff 8934       andi.w    #$00FF,$00FF8934
[00e06602] e140                      asl.w     #8,d0
[00e06604] 8179 00ff 8934            or.w      d0,$00FF8934
[00e0660a] 6000 001a                 bra.w     $00E06626      ; BUG: does not load dest ctrl 

intclk:
[00e0660e] 302f 000a                 move.w    10(a7),d0
[00e06612] 0279 ff00 00ff 8934       andi.w    #$FF00,$00FF8934
[00e0661a] 8179 00ff 8934            or.w      d0,$00FF8934
[00e06620] 3439 00ff 8932            move.w    $00FF8932,d2

dmarec:
[00e06626] 322f 0006                 move.w    6(a7),d1
[00e0662a] 0801 0000                 btst      #0,d1         dst & DMAREC?
[00e0662e] 6700 0030                 beq.w     $00E06660
[00e06632] 302f 0004                 move.w    4(a7),d0
[00e06636] e340                      asl.w     #1,d0
[00e06638] c47c fff0                 and.w     #$FFF0,d2
```
When setting CLKEXT, the routine will jump to dmarec, where d2 is updated, without reading $00FF8932 first.

> That should be fixed on the aranym side, then. 

Yes, sure.

**Comment by mikrosk** [comment]
> That would be the on STE/TT. Aren't the routines supposed to work in that case?

Nope. STE/TT depends solely on presence of either EmuTOS, X-SOUND or STFA (or any other XBIOS emulator I'm unaware of).

> When setting CLKEXT, the routine will jump to dmarec, where d2 is updated, without reading $00FF8932 first.

Oh. So that's _another_ bug then. With addition of the wrong return code and incorrect bits for CLKEXT that makes it three bugs already. I'll have to take take a better look, maybe this code: https://github.com/mikrosk/atari_sound_setup/blob/b55d485ebdab4db1e90d1f154ce23353f4a3c492/atari_sound_setup.h#L587-L596 is total rubbish then and it just fixes the symptom of the bug you have identified.

**Comment by mikrosk** [comment]
> Maybe that replacement is also why SDL sound does not work on the firebee.

Btw, this is quite a good observation, too. Very well possible.

**Comment by th-otto** [comment]
> Nope. STE/TT depends solely on presence of either EmuTOS, X-SOUND or STFA (or any other XBIOS emulator I'm unaware of).

Hm, ok. But i think with a few modifications, that routine could even work there without a driver (when Devconnect is not available on STE/TT, you have to set $FF8921 manually). Atleast you should note that fact in the README maybe.

**Comment by th-otto** [comment]
> is total rubbish then and it just fixes the symptom of the bug you have identified.

Maybe not rubbish. The replacement in SDL also does this: https://github.com/libsdl-org/SDL-1.2/blob/f5f2d3825637169fc8f3ebc6ef0d076916e27e82/src/audio/mint/SDL_mintaudio_xbios.c#L236-L237

This will or in the 0x6000 also when dst is DAC, something that neither TOS 4.04 nor emutos does.

**Comment by mikrosk** [comment]
> Hm, ok. But i think with a few modifications, that routine could even work there without a driver (when Devconnect is not available on STE/TT, you have to set $FF8921 manually). Atleast you should note that fact in the README maybe.

Yeah, that's true. The biggest PITA is emulation of Devconnect(), that one register is basically everything needed for the STE/TT.

I'm not entirely against it but at the same time I want to keep the implementation simple, i.e. not full of `if`s if ste/tt then this else that. Currently the Devconnect() mess is even a bigger problem.

**Comment by mikrosk** [comment]
I've checked your patch. My notes / questions:

> external clock test is skipped if hasFreeFrequencies, since the probed values are not used in that case

True but it may be in the future, see also https://github.com/mikrosk/atari_sound_setup/blob/b55d485ebdab4db1e90d1f154ce23353f4a3c492/atari_sound_setup.h#L435

Also, you have moved the test far to the bottom so the check in `McSn` for `extClock1` and `extClock2` will always succeed, same for `STFA` and then it will be destroyed by `detectFalconClocks`. The idea was to always give priority to hardware and only if there isn't anything connected (or emulated), the XBIOS drivers can offer some comfort.

> inserted stop #0x2300 to be more system friendly while waiting for a timer interrupt

Has this any practical benefit? While I find it a nice idea (perhaps I'll it use elsewhere), in this case we wont save much of anything as it's a one time function (and see below for the rest).

> Changed the bne to bcc. In some cases the exact value of the 200hz counter seems to be missed. That fixes infinite loops in aranym

And also the init `bne` to `bcc` (i.e. `bhs`). I'm not very convinced especially about the init one: how aranym cannot be fast enough to do it in two 200 Hz ticks (`moveq #2,d2`) while 16 MHz Falcon can? Either that `stop` should take care of that (in that case I'm in favour to keep it), or is is that `stop` which makes it so inaccurate (i.e. waking up by an interrupt takes too long) or aranym has some serious timing problems (i.e. not ticking in 200 Hz intervals and/or being asynchronous to CPU ticks).

> For clarity, just returned the number of ticks, and convert that to the clock type afterwards.

That's a nice change, thanks. Although you didn't have to change the registers I guess, it would make the patch cleaner.

> Changed the test for machine type to (cookie_snd & SND_DSP) instead.

Makes sense, too.

Additional notes:
- I'm fine with the C89 changes (assuming for usage in Atari compilers), I started like that, too but quickly got bored with typing all of those `/* */` but please don't reformat the code (`{` at new lines, `*` by name and not by type, operators before new line, ...)
- I'm divided on the bitfieldisation of `AudioFormat`. While it simplifies some things it also implies that it is possible to combine the values together, which is especially confusing for `AudioFormatCount` (the whole idea of that one was to be able to add a check/assert "am I handling all the available formats?" in case this will ever turn into a library)

**Comment by mikrosk** [comment]
> When setting CLKEXT, the routine will jump to dmarec, where d2 is updated, without reading $00FF8932 first.

Btw have you checked what exactly it is in `d2` at that time? If I understand the code correctly, `or.w d0,d2` (DAC output) basically keeps the original value in `d2`  (`d0` is zero for DMAPLAY), so whatever is in `d2` is put into $00FF8932. I'm surprised how little damage it does, perhaps it is zero, i.e. DMA output is streamed everywhere?

**Comment by th-otto** [comment]
> Also, you have moved the test far to the bottom so the check in `McSn` for `extClock1` and `extClock2` will always >succeed, same for `STFA` and then it will be destroyed by `detectFalconClocks`.

No it won't, since in both cases, hasFreeFrequencies is set, and then detectFalconClocks is not called anymore.

>it may be in the future

But currently it isn't. If the logic is changed later to support more hardware, that of course has to be checked again.

>The idea was to always give priority to hardware and only if there isn't anything connected (or emulated), the XBIOS drivers can offer some comfort.

But the tests will take between 36+39 and 2*50 ticks, or 375-500ms, that is a noticable delay. If we already know that the values aren't needed, it can be avoided.

> Has this any practical benefit?

It prevents emulators from running at 100% CPU.

> And also the init `bne` to `bcc` (i.e. `bhs`). I'm not very convinced especially about the init one: how aranym cannot be fast >enough to do it in two 200 Hz ticks (`moveq #2,d2`) while 16 MHz Falcon can?

Yes, that's something i dont' quite understand either. But fact is that currently aranym in some cases (and in rare cases also Hatari) hangs on this test forever.

> or is is that `stop` which makes it so inaccurate

No, its not the "stop". I've inserted that later.

>  Although you didn't have to change the registers I guess, it would make the patch cleaner.

Not strictly, yes. It's just a small optimization because the code now only uses registers (except for d2) that are scratch registers anyway and don't have to be saved.

>  please don't reformat the code (`{` at new lines, `*` by name and not by type, operators before new line, ...)

Yes, sorry about that. If needed, i can change it back to the original formatting.

>     * I'm divided on the bitfieldisation of `AudioFormat`.

I found that easier, but it is not strictly needed. Again, i could change that back if wanted.

**Comment by th-otto** [comment]
> Btw have you checked what exactly it is in `d2` at that time?

d2 in TOS 4.04 is not changed in the xbios trap, and also not in devconnect before that label is reached, so that simply depends on whatever the application had in that register before.

**Comment by th-otto** [comment]
Ok, here is the revived version. Also as patch (but the patch is larger than the original file ;)

Changed the formatting back, and also the array for formatsAvailable. I've kept the the changes for the c99-isms though; since it is a header file, it would otherwise essentially prevent users from using certain warning options.

[atari_sound_setup.h.txt](https://github.com/mikrosk/atari_sound_setup/files/14846239/atari_sound_setup.h.txt)
[atari_sound_setup.patch.txt](https://github.com/mikrosk/atari_sound_setup/files/14846242/atari_sound_setup.patch.txt)

**Comment by mikrosk** [comment]
> Hm, ok. But i think with a few modifications, that routine could even work there without a driver (when Devconnect is not available on STE/TT, you have to set $FF8921 manually).

I have been thinking about this and no, the behaviour is correct. Because if you get TRUE here, it also implies that you are free to call any _other_ sound XBIOS functions by yourself. If the init did some direct hardware access, you, as the user, would need to do all the checking for the cookies again. But you are right, I should rephrase README a bit.

> No it won't, since in both cases, hasFreeFrequencies is set, and then detectFalconClocks is not called anymore.
[...]
> But currently it isn't. If the logic is changed later to support more hardware, that of course has to be checked again.
[...]
> But the tests will take between 36+39 and 2*50 ticks, or 375-500ms, that is a noticable delay. If we already know that the values aren't needed, it can be avoided.

I tried to implement this as future-proof as possible (naive, I know). The first (and easiest to fix) problem here is that the `if` is still there so it checks for the clocks to be zero (which always are). The second problem is that `hasFreeFrequency` has no relationship with the external clock. Currently our code just forces the `Soundcmd` way but as soon as I add some function for selecting/preferring one over another I will have to re-add all that code again. Maybe there could be a flag for the init function, like `useFreeFrequencyIfAvailable` and that would make it very explicit.

> It prevents emulators from running at 100% CPU.

For that 0.5s you mean ;) As for the `bne`s, I don't know, I'm still not convinced it is a good idea. Yeah, it solves your problem _right now_ but in the long run, it hides a potentially serious problem in Aranym (and/or Hatari). Introducing that `useFreeFrequencyIfAvailable` would actually solve this dilemma, too: the user could decide whether he wants to skip the check explicitly, even based on Aranym's `_MCH` cookie.

Cool, now the patch looks much cleaner. I start to think that creating a PR would be an easier way to do a review. ;)

```C
if((long) bufs == -32)
		bufs = (char*)Malloc(TEST_BUFSIZE);
```
This is to support (STE) TOS 1.6x ? If so, perhaps this should be done via `Sversion`.

```C
		/* X-Sound doesn't set _SND (MacSound does) */
		snd |= SND_PSG | SND_8BIT;
```
I guess you have removed the `if` since you set it to `SND_PSG` by default? In such case this should contain only `SND_8BIT`, right?

```C
	if (!(snd & SND_8BIT)) {
		AtariSoundSetupDeinitXbios();
		return 0;
```
I think this is not correct: before we bailed out only in ST case (i.e. no cookie set), now we insist to have 8-bit samples present. It's possible that some driver doesn't set 8-bit but does set 16-bit.

**Comment by th-otto** [comment]
>  If the init did some direct hardware access, you, as the user, would need to do all the checking for the cookies again.

Yes, but that's doable. Atleast that's what i've done in SDL now. But lets maybe wait until after some testing (see https://www.atari-forum.com/viewtopic.php?p=461325#p461325)

> `if` is still there so it checks for the clocks to be zero (which always are). The second problem is that `hasFreeFrequency` has no relationship with the external clock.

Of course it has relationship. In https://github.com/mikrosk/atari_sound_setup/blob/b55d485ebdab4db1e90d1f154ce23353f4a3c492/atari_sound_setup.h#L485 the `if` part does not use the external clocks.

> I'm still not convinced it is a good idea. Yeah, it solves your problem _right now_ but in the long run, it hides a potentially serious problem in Aranym (and/or Hatari).

Yes, that's true. But i have no idea why and where that happens. And even if i find the cause and can fix it, it would still not work for users using current versions of aranym. Same for Hatari (although there it only happens on rare cases). So for now, i just would ask to keep the `bcc`. It should give the same result (unless the counter wraps around after ~124 days ;)


> This is to support (STE) TOS 1.6x ? If so, perhaps this should be done via `Sversion`.

Yes, it checks whether Mxalloc is available at all. And no, you should not use `Sversion` for it, that check is all it takes.
 
> I guess you have removed the `if` since you set it to `SND_PSG` by default? In such case this should contain only `SND_8BIT`, right?

Hm ok, but the result will be the same. The code does not care about the `SND_PSG` bit.
 
> I think this is not correct: before we bailed out only in ST case (i.e. no cookie set), now we insist to have 8-bit samples present. It's possible that some driver doesn't set 8-bit but does set 16-bit.

Ok. I interpreted `SND_8BIT` for `dma sound is available`, which is what the routines require. But you are right, checking both bits would be cleaner.

**Comment by th-otto** [comment]
Something i just noticed:
https://github.com/mikrosk/atari_sound_setup/blob/b55d485ebdab4db1e90d1f154ce23353f4a3c492/atari_sound_setup.h#L376-L377

But according to SDL https://github.com/libsdl-org/SDL-1.2/blob/f5f2d3825637169fc8f3ebc6ef0d076916e27e82/src/audio/mint/SDL_mintaudio_mcsn.h#L49-L55 the value for Falcon should be 3, not 2?

Edit: args, forget it. I counted wrong.

**Comment by mikrosk** [comment]
Latest HEAD contains three fixes:

- 6258 Hz is no longer selected on Falcon
- CLKEXT is activated on all TOS 4.0x versions, not only on 4.04
- source path is initialised properly (`d2` is properly preloaded)

Harmless on EmuTOS, CT60 TOS or any other patched TOS and tailored for TOS 4.0x. Close call.

**Comment by th-otto** [comment]
Hu, that FalconDevconnectExtClk function really looks ugly... And i'm not sure it is the right thing to do. It will now access the hardware, even if a installed driver might be doing something completely different. But atleast it should work with plain TOS now. How i hate to workaround all those TOS bugs... Maybe it would be cleaner to just replace the whole Devconnect function, and do what EmuTOS does?


But just another question. Did you ever run your led_blur demo on a stock Falcon or only on CT60? I'm asking because when i use Hatari to emulate a 32Mhz Falcon, i get only around 2-3 FPS even with music turned off, and even less later. And with music on, it sounds really strange, as if the playback is looped before the buffer is filled again.

**Comment by th-otto** [comment]
>  how aranym cannot be fast enough to do it in two 200 Hz ticks (`moveq #2,d2`) while 16 MHz Falcon can?

The main problem seems to be not that aranym is not fast enough, but the SDL timer is run only every 10 ms: https://github.com/aranym/aranym/blob/84983cc188f29f3f1875b872266841baba609ad3/src/main.cpp#L283-L287

So essentially it runs at 100Hz, and then generates 2 interrupts on each invocation. I've also written a small test program to verify it:

```
#include <stdio.h>
#include <mint/osbind.h>
#include <mint/arch/nf_ops.h>

unsigned long counter;

static void printit(unsigned long hz200)
{
	++counter;
	nf_debugprintf("tick %lu: %lu\n", counter, hz200);
}

static long hz200test(void)
{
	register int ret __asm__("d0");

	__asm__ volatile(
		"	lea		0x4ba.w,%%a2\n"
		"	move.l	#200,%%d2\n"    /* run for 200 ticks (1 sec) */
		"	move.l	(%%a2),%%d1\n"
		"	move.l	%%d1,%%d3\n"
		"	add.l	%%d1,%%d2\n"
		"tloop:\n"
		"	stop    #0x2300\n"
		"	move.l	(%%a2),%%d0\n"
		"	cmp.l	%%d0,%%d2\n"
		"	bls.s	tstop\n"
		"	cmp.l	%%d0,%%d1\n"
		"	beq.s	tloop\n"
		"   move.l  %%d0,-(%%sp)\n"
		"   move.l  %%d0,-(%%sp)\n"
		"   bsr     %1\n"
		"   addq.l  #4,%%sp\n"
		"   move.l  (%%sp)+,d1\n"
		"   bra.s   tloop\n"
		"tstop:\n"
		"	sub.l	%%d3,%%d0\n"	/* timelength */

		: "=r"(ret)	/* outputs */
		: "mi"(printit) /* inputs */
		: __CLOBBER_RETURN("d0") "d1", "d2", "d3", "a0", "a1", "a2", "cc" AND_MEMORY
	);

	return ret;
}


int main(void)
{
	unsigned long ticks = Supexec(hz200test);
	nf_debugprintf("total ticks: %lu\n", ticks);
	return 0;
}
```

(using nf_debugprint instead of printf, because you won't see any output in toswin until the function returns from supervisor mode)

It prints something like:
```
tick 1: 3497
tick 2: 3499
tick 3: 3501
...
tick 98: 3693
total ticks: 200
```
You can see that the 200Hz counter is incremented in steps of 2. Omitting the stop instruction does not change that behaviour.

BTW, the correct test for the loop would be bhi not bcc. With bcc the timeout would be 1 tick more than originally (although that doesn't change the logic)

Update: changing the interval to 5ms does not work either, because the clock resolution is 100 Hz on linux.

**Comment by mikrosk** [comment]
What a bummer. As this really isn't easily fixable I'm thinking whether it even makes sense to test at all. Can't we just hardcode if mch == MCH_ARANYM then extClock = 1 ?

**Comment by th-otto** [comment]
That would only work if you don't set the _MCH cookie to falcon in the config file. And you may have to also change all your `if (cookie_mch == MCH_FALCON)` to `if (cookie_mch == MCH_FALCON || cookie_mch == MCH_ARANYM)`. Apart from that, i still dislike the idea of checking the _MCH cookie at all in sound related routines.

**Comment by mikrosk** [comment]
> It will now access the hardware, even if a installed driver might be doing something completely different. 

That's the beauty of it, Falcon can't do anything different. If you want CLKEXT to work, it has to set $ffff8930's bits to $6000, so there's no harm done doing that in advance (other possible TOS / driver implementations can't depend on some initial value to be always set so they will have to reinit the register anyway). And of course setting `d2` is totally harmless.

> Maybe it would be cleaner to just replace the whole Devconnect function, and do what EmuTOS does?

I've thought if that, too. Coding something like [FPATCH2](https://public.websites.umich.edu/~archive/atari/Falcon/Utilities/fpatch2.zip)'s successor. That way also the Devconnect return value problem could be fixed. If we wanted to be ambitious, we could include an XBIOS for STE/TT there as well so any clean software (SDL) could just depend on it.

> But just another question. Did you ever run your led_blur demo on a stock Falcon or only on CT60? I'm asking because when i use Hatari to emulate a 32Mhz Falcon, i get only around 2-3 FPS even with music turned off, and even less later. And with music on, it sounds really strange, as if the playback is looped before the buffer is filled again.

Sure, just yesterday on CT60 when testing the CLKEXT changes (to be sure that at 44100 I don't get mute as it was happening without ADC init). Don't forget that the whole 320x240 screen is _vertically_ rendered and then _vertically_ copied, all in 16-bit hicolor. I'm not surprised at all at its slow performance.

**Comment by mikrosk** [comment]
> Apart from that, i still dislike the idea of checking the _MCH cookie at all in sound related routines.

Yeah, I'm not huge fan either. In the Devconnect() case it makes sense (they are Falcon hardware registers after all), in the external clock case not so much, as we are aware of different implementations (which are responding to the GPIO calls).

One elegant solution would be if Aranym (and/or Hatari) just set the `SND_EXT` bit in `_SND` and offered the `Soundcmd` extension(s). After adding the init flag (useFreeFrequency) this would be a clean fix because `hasFreeFrequency` would be true in Aranym (and/or Hatari) and we would use `_SND` for the purpose it was meant to be.

**Comment by th-otto** [comment]
But the _SND cookie is not set by Aranym, it is set by the OS. And SND_EXT indicates that a separate driver is installed, which is not the case.

**Comment by mikrosk** [comment]
Yes, it would definitely require some effort on Aranym side. :-/

**Comment by th-otto** [comment]
No, it doesn't, because Aranym cannot replace the XBIOS.

**Comment by mikrosk** [comment]
Same as it can't patch TOS. :) I'm aware of the amount of work. The normal solution would be to create a driver but that would be again the same situation as with hostfs, e.g. separate versions for TOS/MagiC and FreeMiNT.

**Comment by th-otto** [comment]
That patches are only meant to make TOS ready for 040. Maybe patching of the Devconnect function could be done there, too. I think it would be sufficient to just change the branch at
```
[00e0660a] 6000 001a                 bra.w     $00E06626 
```
But it is not suitable to completely replace several XBIOS functions.

**Comment by th-otto** [comment]
> Sure, just yesterday on CT60 when testing the CLKEXT changes

I meant when running as 030, not 060. I know that the emulation of 030 in Hatari is not yet cycle-exact, but i wonder if the results on real hw are similar. Oh and i ran it in 256 color resolution, not hicolor, that might require some additional work in the demo routines and/or in SDL for rendering.

**Comment by mikrosk** [comment]
> I meant when running as 030, not 060. I know that the emulation of 030 in Hatari is not yet cycle-exact, but i wonder if the results on real hw are similar.

I'm pretty sure they are but if you like, I can give it a go.

> Oh and i ran it in 256 color resolution, not hicolor, that might require some additional work in the demo routines and/or in SDL for rendering.

This should be the case only for 640x480, if it's running in 8-bit 320x240 that's quite a problem because than it _dithers_ from 16-bit to 8-bit _and_ doing 8-bit C2P afterwards.

**Comment by th-otto** [comment]
Yes, but as you surely know, there is no 16bit color resolution in EmuTOS yet ;)

Edit: using TOS 4.04 and hicolor does not make much difference. Still 2-3 FPS

**Comment by mikrosk** [comment]
I have included most of your changes except:

> external clock test is skipped if hasFreeFrequencies, since the probed values are not used in that case

> Changed the test for machine type to (cookie_snd & SND_DSP) instead. Not entirely sure whether there is a better way, but atleast it should not depend on the machine type (previously it would be skipped if you have that set to MCH_ARANYM, and also on clones like Hades/Milan/Firebee),

These go hand in hand. After some thinking I have decided to keep the current state:
- `ExternalClockTest` does access hardware directly, so it _must_ be executed only on a Falcon compatible machine which is currently only Aranym (Milan/Hades use the extended XBIOS anyway and FireBee, well, in theory, one day, maybe but not today...).
- `SND_DSP` can be easily set for a PCI addon card (or whatever). It says nothing about availability of the DSP port and most importantly, about hardware registers. I would imagine that when this cookie value is set, I can only safely call all those DSP XBIOS functions. However I have realised that I can't rely neither on `SND_DSP` nor `MCH_FALCON` for save/restore via `Gpio()` as I am calling it then also for `SND_EXT`.

> the externalClockTest function slightly changed

Feel free to create a PR for the aranym compatibility. Ideally, if we could get this function rewritten in a OS-friendlier way (although it's not so easy as calling XBIOS is a non-trivial overhead by itself). That would be a real incentive to alter the original routine because it would work on other machines than Falcon plus it could serve as an example how to verify even the standard frequencies (49170 Hz etc) on any machine.

**Comment by mikrosk** [comment]
Oh and of course thanks for the patch, not only it made the routines better but it also forced me to rethink some of my reasoning!

**Comment by th-otto** [comment]
>     * `ExternalClockTest` does access hardware directly, so it _must_ be executed only on a Falcon compatible machine which is currently only Aranym

Yes, ok. I already noted that i wasn't sure whether using SND_DSP is the correct way. OTOH, the external clock sources currently come from the GPIO pins of the DSP, so this is somewhat related. I'm just asking to change the branch conditions to bhi to prevent hangs on Aranym (their might be reasons to have to set the cookie value to 3 on aranym, because of other programs that don't recognize the aranym specific value).

Anyway, thanks for your time to having looked after this.
